### ISSUE TITLE
Error in UseMethod("predict") :    no applicable method for 'predict' applied to an object of class "tlearner"

### ISSUE THREAD

**Issue by dbroockman** [xnie/rlearner#3]
The ReadMe has the following example:

```
tlearner_fit = tlearner_cv(data$x, data$w, data$y, model_specs=model_specs)
tlearner_tau_hat = predict(tlearner_fit, data$x)
```

However, when I run this code, I see the following error:
```
Error in UseMethod("predict") : 
  no applicable method for 'predict' applied to an object of class "tlearner"
```

**Comment by xnie** [comment]
Thanks for bringing this to our attention! Due to version issues and package limitations, we are no longer supporting caret-based estimators, and are planning on updating the repository to reflect this change. However, this does not affect replicating the results from the paper as the paper does not use caret-based code.
